# -*- coding: utf-8 -*-
"""RAG WORKFLOW -1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E8YK9DN9GWcRA6GOGhXb5scOcb6rCYhc

# **install libraries**
"""

!pip install pypdf
!pip install sentence-transformers
!pip install faiss-cpu

"""# **Upload IRS PDF**"""

from google.colab import files

uploaded = files.upload()

"""# **Read PDF**"""

!pip install pypdf

from pypdf import PdfReader

reader = PdfReader("Employee-Handbook.pdf")

print("Total Pages:", len(reader.pages))

text = ""

for page in reader.pages:
    page_text = page.extract_text()

    if page_text:
        text += page_text

print(text[:1000])

"""# **Create Chunks**"""

chunks = []

chunk_size = 500

for i in range(0, len(text), chunk_size):
    chunks.append(text[i:i+chunk_size])

print("Total Chunks:", len(chunks))

print(chunks[0])

"""# **Install RAG Libraries**"""

!pip install sentence-transformers
!pip install faiss-cpu

"""# **Create Embeddings**"""

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

embeddings = model.encode(chunks)

print(embeddings.shape)

"""# **Store in FAISS (VECTOR) DATA BASE**"""

import faiss
import numpy as np

dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(np.array(embeddings))

print("FAISS Database Created")

"""# **I some Ask Question**"""

query = "How we expect manager to lead  employee"

"""# **Search Relevant Chunks**"""

query_embedding = model.encode([query])

D, I = index.search(np.array(query_embedding), k=3)

for idx in I[0]:
    print("\n")
    print(chunks[idx])
    print("="*50)